project:
  type: book
book:
  cover-image: images/Rtree.png
  title: "NavigatoR: Plotting Your Course Through R Fundamentals"
  sidebar:
    logo: images/NavigatoR.png
  author: Daniel Väisänen
  date: 6/11/2024
  chapters:
  - index.qmd
  - 00_preface.qmd
  - 01_install.qmd
  - 02_project_setup.qmd
  - 03_basics.qmd
  - 04_quarto_etc.qmd
  - 05_version_control.qmd
  - 06_tidy_data.qmd
  - 07_exploratory_data_analysis.qmd
  - 08_tables_plots.qmd
  - 09_assemble_workflow.qmd
  - 10_generative_ai.qmd
  - 11_usefull_packages.qmd
  - references.qmd
bibliography: references.bib
format:
  html:
    df-print: kable
    code-link: true
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: include/webex.css
    include-after-body: include/webex.js
  pdf:
    documentclass: scrreprt
editor: source
execute:
  echo: true
  warning: false
  message: false