# Pre-render step: build the map used by link-functions.lua
#
# Quarto's `code-link: true` links function calls inside executed code chunks.
# It does not touch inline code in prose, so `mutate()` in a sentence stays
# unlinked. This script closes that gap: it collects every inline `fn()` used
# in the book, resolves each to its documentation URL with downlit, and writes
# a Lua table that the filter reads.
#
# Resolution follows R's own rules: a function is attributed to the first
# package on the search path that exports it, so `filter()` resolves to dplyr
# rather than stats, exactly as it would when the reader runs the code.

suppressPackageStartupMessages({
  # the order here defines the search path, and therefore who wins a name clash
  library(tidyverse)
  library(palmerpenguins)
  library(here)
  library(janitor)
  library(skimr)
  library(naniar)
  library(patchwork)
  library(gt)
  library(gtsummary)
  library(webexercises)
  library(marginaleffects)
  library(targets)
})

# GGally and Hmisc are used but not attached in the book, so look them up
# without attaching them and disturbing the search path above
optional_packages <- c(
  "GGally", "Hmisc", "broom", "testthat", "DT", "flextable",
  "usethis", "readxl", "haven", "writexl", "rprojroot", "knitr", "quarto",
  "marginaleffects", "emmeans", "performance", "parameters", "lme4",
  "broom.mixed", "rsample", "targets", "tarchetypes", "renv",
  "dagitty", "ggdag", "EValue", "MatchIt", "cobalt", "reprex", "summarytools",
  "tidymodels", "recipes", "parsnip", "workflows", "yardstick"
)

qmd_files <- list.files(".", pattern = "\\.qmd$", full.names = TRUE)

# Inline code is written between single backticks. Pull out the spans that look
# like a function call: optionally package-qualified, ending in ().
extract_calls <- function(path) {
  lines <- readLines(path, warn = FALSE)

  # drop fenced code chunks - those are already handled by code-link
  in_chunk <- cumsum(grepl("^\\s*```", lines)) %% 2 == 1
  lines <- lines[!in_chunk & !grepl("^\\s*```", lines)]

  spans <- unlist(regmatches(lines, gregexpr("`[^`]+`", lines)))
  spans <- gsub("^`|`$", "", spans)
  spans[grepl("^([A-Za-z][A-Za-z0-9.]*::)?[A-Za-z._][A-Za-z0-9._]*\\(\\)$", spans)]
}

calls <- sort(unique(unlist(lapply(qmd_files, extract_calls))))
message("Found ", length(calls), " distinct inline function calls.")

# Which package does an unqualified name come from?
package_of <- function(name) {
  found <- utils::getAnywhere(name)
  attached <- sub("^package:", "", found$where[grepl("^package:", found$where)])
  if (length(attached)) {
    return(attached[[1]])
  }
  for (pkg in optional_packages) {
    if (requireNamespace(pkg, quietly = TRUE) &&
      name %in% getNamespaceExports(pkg)) {
      return(pkg)
    }
  }
  namespaced <- sub("^namespace:", "", found$where[grepl("^namespace:", found$where)])
  if (length(namespaced)) namespaced[[1]] else NA_character_
}

resolve <- function(call) {
  if (grepl("::", call, fixed = TRUE)) {
    return(downlit::autolink_url(call))
  }
  name <- sub("\\(\\)$", "", call)
  pkg <- tryCatch(package_of(name), error = function(e) NA_character_)
  if (is.na(pkg)) {
    return(NA_character_)
  }
  tryCatch(
    downlit::autolink_url(paste0(pkg, "::", name, "()")),
    error = function(e) NA_character_
  )
}

# Some functions are documented but not exported - dplyr's join helpers
# closest() and overlaps() are the case here - so getAnywhere() cannot see
# them. Fall back to asking downlit directly, package by package.
resolve_by_search <- function(call) {
  name <- sub("\\(\\)$", "", call)
  candidates <- c(
    sub("^package:", "", grep("^package:", search(), value = TRUE)),
    optional_packages
  )
  for (pkg in candidates) {
    url <- tryCatch(
      downlit::autolink_url(paste0(pkg, "::", name, "()")),
      error = function(e) NA_character_
    )
    if (!is.na(url)) {
      return(url)
    }
  }
  NA_character_
}

urls <- vapply(calls, resolve, character(1), USE.NAMES = TRUE)

missing <- is.na(urls)
if (any(missing)) {
  urls[missing] <- vapply(
    names(urls)[missing], resolve_by_search, character(1),
    USE.NAMES = FALSE
  )
}

urls <- urls[!is.na(urls)]

message("Resolved ", length(urls), " of ", length(calls), " to a URL.")

unresolved <- setdiff(calls, names(urls))
if (length(unresolved)) {
  message("No documentation link for: ", paste(unresolved, collapse = ", "))
}

escape_lua <- function(x) gsub('"', '\\\\"', x, perl = TRUE)

entries <- sprintf(
  '  ["%s"] = "%s",',
  escape_lua(names(urls)),
  escape_lua(unname(urls))
)

writeLines(
  c(
    "-- Generated by R/build_function_links.R - do not edit by hand.",
    "return {",
    entries,
    "}"
  ),
  "_function_links.lua"
)

message("Wrote _function_links.lua")
